version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
  - package-ecosystem: gomod
    directory: /runner
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
  - package-ecosystem: gomod
    directory: /broker
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
  - package-ecosystem: docker
    directory: /runner
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
  - package-ecosystem: docker
    directory: /broker
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
  - package-ecosystem: docker
    directory: /nginx
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
