apiVersion: networking.gke.io/v1
kind: GCPGatewayPolicy
metadata:
  name: bunshin-internal
  namespace: bunshin
spec:
  default:
    allowGlobalAccess: true
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: bunshin-internal
