apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: bunshin
  labels:
    app: nginx
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"8080":{"name":"${NGINX_NEG_NAME}"}}}'
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
