name: Integration

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "broker/**"
      - "runner/**"
      - "nginx/**"
      - "integration/**"
      - "compose.yml"
      - "init/**"
      - ".env.example"
      - ".github/workflows/integration.yml"

permissions:
  contents: read

jobs:
  integration-go:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - uses: crazy-max/ghaction-github-runtime@04d248b84655b509d8c44dc1d6f990c879747487 # v4.0.0
      - name: Build integration images
        run: docker compose --env-file .env.example --profile integration build nginx broker runner-1 runner-2 integration-test forward-cert forward-target
      - name: Run integration tests
        run: docker compose --env-file .env.example --profile integration run --rm integration-test
      - name: Cleanup
        if: always()
        run: docker compose --env-file .env.example --profile integration down -v
