name: Nginx

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "nginx/**"
      - ".github/workflows/nginx.yml"

permissions:
  contents: read

jobs:
  nginx-config-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build config-test stage
        run: docker build --target config-test nginx/
